### ISSUE TITLE
Баг: Ошибка авторизации

### ISSUE THREAD

**Issue by miirsery** [anime-team-pet-projects/lavochki-nsk#170]
Ошибка при попытке авторизоваться через теграм.
`/api/v1/users`
![image](https://user-images.githubusercontent.com/57665901/215343727-a36708d8-d5e0-420c-89ad-28cedf18f02b.png)

**Comment by s1veme** [comment]
Требуются уточнения. Баг не удалось повторить.

@miirsery

**Comment by s1veme** [comment]
Закрыт. Не удалось повторить.
