### ISSUE TITLE
Refactor: Переработать пагинацию

### ISSUE THREAD

**Issue by miirsery** [anime-team-pet-projects/lavochki-nsk#242]
`/api/v1/benches/moderation` на примере данного `endpoint`

Сейчас приходит пагинация в таком формате
![image](https://github.com/anime-team-pet-projects/lavochki-nsk/assets/57665901/6f03ce4e-76e5-499e-b76d-7c9921cb6c8b)

Хотелось бы в итоге увидеть это:
```
pagination: {
  count: number
  count_all_pages: number
  per_page: number
  current_page: number
}

items: any[]
```

Привести всю пагинацию к одному виду

**Comment by s1veme** [comment]
Обновлено: https://github.com/anime-team-pet-projects/lavochki-nsk/commit/052afe90b463e92e5c5eb8a575fd0ce853f8c6fc;
